spring:
  security:
    user:
      name: user
      password: password
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Oris-db?stringtype=unspecified
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
  jpa:
    show-sql: true
jwt:
  secret:
    access: =qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: =zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==